- name: parser example
  hosts: all
  gather_facts: no
  connection: local



  tasks:


   - name: Close task
     snow_record:
      state: present
      table: sc_req_item
      number: RITM0010032
      username: "admin"
      password: "Cq8AlqODRgd2"
      instance: "{{ req_item_number }}"
      data:
        state: 3
        work_notes: "Change Closed"
        
